services:
    postgres:
        container_name: database
        ports:
            - "5431:5432"
        image: postgres
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        volumes:
            - ./docker_test_db:/var/lib/postgresql/data
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        # command: npm start
        ports:
            - "7999:8000"
        environment:
            DATABASE_URL: "${DATABASE_URL}"
            PORT: "${PORT}"
        depends_on:
            - postgres
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        # command: npm start
        ports:
            - "4174:4173"
        # environment:
        #     VITE_SERVER_URL: "${VITE_SERVER_URL}"
        depends_on:
            - server
